try{
    throw "";
}
catch(e){
    console.log("An error occurred");
}
finally{
    console.log("Errors processed");
}