try{
    throw "";
}
catch(e){
    console.log("Произошла ошибка");
}
finally{
    console.log("Ошибки обработаны");
}